---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
<<<<<<< HEAD
  - HUGO_VERSION=0.81.0
=======
  - HUGO_VERSION=0.80.0
>>>>>>> main
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
<<<<<<< HEAD
version: 0.81.0
=======
version: 0.80.0
>>>>>>> main
